packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - esbuild
  - '@ffmpeg-installer/darwin-arm64'
  - '@ffprobe-installer/darwin-arm64'
ignoredBuiltDependencies:
  - better-sqlite3
  - puppeteer
  - '@revideo/telemetry'
